// Biome definitions — visual themes, tile palettes, ambient particle configs

export const BIOMES = {
    graveyard: {
        id: 'graveyard',
        name: 'The Graveyard',
        description: 'Ancient burial grounds shrouded in mist.',
        tileColors: ['#2c4a2c', '#345434', '#2e4a2e', '#284028'],
        gridColor: 'rgba(255,255,255,0.06)',
        bgColor: '#142a24',
        stoneColor: '#2a2a2a',
        propColors: {
            stone: '#2a2a2a',
            stoneHighlight: '#6a7060',
            detail1: '#3a4a3a',
            detail2: '#ccccbb',
            glow: '#88cc99',
            crack: '#0e1a0e',
        },
        ambient: {
            type: 'mist',
            color: '#88AA88',
            count: 28,
            speed: 15,
            size: [4, 12],
            alpha: 0.30,
        },
        hazards: {
            type: 'graveyard_fog',
            interval: [25, 35],
            count: [2, 3],
        },
    },
    volcano: {
        id: 'volcano',
        name: 'The Volcano',
        description: 'Molten earth cracks beneath your feet.',
        tileColors: ['#48241a', '#54301c', '#4e2a18', '#421e10'],
        gridColor: 'rgba(255,100,0,0.04)',
        bgColor: '#2a1208',
        stoneColor: '#3a2a1a',
        propColors: {
            stone: '#1a0e0a',
            stoneHighlight: '#3a2020',
            detail1: '#4a3020',
            detail2: '#555555',
            glow: '#FF4400',
            crack: '#FF6622',
            lava: '#FF4422',
            obsidian: '#1a0a2a',
        },
        ambient: {
            type: 'ember',
            color: '#FF6622',
            count: 24,
            speed: 40,
            size: [2, 5],
            alpha: 0.55,
        },
        hazards: {
            type: 'lava_crack',
            interval: [12, 18],
            count: [1, 1],
        },
    },
    void: {
        id: 'void',
        name: 'The Void',
        description: 'Reality fractures at the edge of existence.',
        tileColors: ['#1f1f4a', '#25254e', '#21214a', '#1c1c40'],
        gridColor: 'rgba(100,100,255,0.06)',
        bgColor: '#161630',
        stoneColor: '#1a1a3a',
        propColors: {
            stone: '#1a1a3a',
            stoneHighlight: '#2a2a5a',
            detail1: '#3333aa',
            detail2: '#6644aa',
            glow: '#6666FF',
            crystal: '#8844ff',
            rune: '#3333bb',
        },
        ambient: {
            type: 'spark',
            color: '#6666FF',
            count: 35,
            speed: 60,
            size: [1.5, 4],
            alpha: 0.70,
        },
        hazards: {
            type: 'void_rift',
            interval: [20, 20],
            count: [1, 1],
        },
    },
};

export const BIOME_LIST = ['graveyard', 'volcano', 'void'];
