// Pure data: weapon definitions + evolution table
// Levels 1-8, evolution at level 8 + matching passive

export const WEAPONS = {
    pistol: {
        id: 'pistol',
        name: 'Pistol',
        description: 'Reliable sidearm. Fires toward cursor.',
        icon: '🔫',
        pattern: 'aimed_single',
        baseDamage: 10,
        baseCooldown: 0.4,
        projectileSpeed: 600,
        projectileRadius: 4,
        projectileLifetime: 1.2,
        projectileCount: 1,
        pierce: 0,
        spread: 0,
        color: '#FFDD44',
        knockbackDist: 4,
        knockbackSpeed: 200,
        evolvesWithPassive: 'piercing',
        evolutionId: 'railgun',
    },
    shotgun: {
        id: 'shotgun',
        name: 'Shotgun',
        description: 'Spread of pellets. Devastating up close.',
        icon: '💥',
        pattern: 'aimed_spread',
        baseDamage: 6,
        baseCooldown: 0.8,
        projectileSpeed: 500,
        projectileRadius: 3,
        projectileLifetime: 0.5,
        projectileCount: 5,
        pierce: 0,
        spread: 0.35, // radians total arc
        color: '#FF8844',
        knockbackDist: 10,
        knockbackSpeed: 300,
        evolvesWithPassive: 'spread',
        evolutionId: 'flak_cannon',
    },
    smg: {
        id: 'smg',
        name: 'SMG',
        description: 'Rapid fire with slight spread.',
        icon: '🔥',
        pattern: 'aimed_single',
        baseDamage: 4,
        baseCooldown: 0.12,
        projectileSpeed: 550,
        projectileRadius: 3,
        projectileLifetime: 0.8,
        projectileCount: 1,
        pierce: 0,
        spread: 0.15,
        color: '#FFAA22',
        knockbackDist: 4,
        knockbackSpeed: 200,
        evolvesWithPassive: 'haste',
        evolutionId: 'minigun',
    },
    rocket: {
        id: 'rocket',
        name: 'Rocket Launcher',
        description: 'Slow rocket, big explosion on impact.',
        icon: '🚀',
        pattern: 'aimed_single',
        baseDamage: 30,
        baseCooldown: 2.0,
        projectileSpeed: 250,
        projectileRadius: 6,
        projectileLifetime: 2.0,
        projectileCount: 1,
        pierce: 0,
        spread: 0,
        aoeRadius: 80,
        color: '#FF4422',
        knockbackDist: 40,
        knockbackSpeed: 500,
        evolvesWithPassive: 'damage',
        evolutionId: 'mirv',
    },
    lightning: {
        id: 'lightning',
        name: 'Lightning',
        description: 'Chain lightning to nearest enemy.',
        icon: '⚡',
        pattern: 'auto_chain',
        baseDamage: 12,
        baseCooldown: 1.0,
        chainRange: 150,
        chainCount: 2,
        color: '#88CCFF',
        knockbackDist: 0,
        knockbackSpeed: 0,
        evolvesWithPassive: 'area',
        evolutionId: 'thunderstorm',
    },
    flamethrower: {
        id: 'flamethrower',
        name: 'Flamethrower',
        description: 'Short-range cone of fire toward cursor.',
        icon: '🔥',
        pattern: 'aimed_cone',
        baseDamage: 3,
        baseCooldown: 0.05,
        projectileSpeed: 300,
        projectileRadius: 4,
        projectileLifetime: 0.3,
        projectileCount: 1,
        spread: 0.4,
        color: '#FF6622',
        knockbackDist: 2,
        knockbackSpeed: 100,
        evolvesWithPassive: 'duration',
        evolutionId: 'inferno',
    },
    boomerang: {
        id: 'boomerang',
        name: 'Boomerang',
        description: 'Thrown toward nearest enemy, returns.',
        icon: '🪃',
        pattern: 'auto_boomerang',
        baseDamage: 15,
        baseCooldown: 1.5,
        projectileSpeed: 350,
        projectileRadius: 8,
        projectileLifetime: 2.0,
        pierce: 99,
        color: '#44DDAA',
        knockbackDist: 18,
        knockbackSpeed: 250,
        evolvesWithPassive: 'movespeed',
        evolutionId: 'chakram',
    },
    orbitals: {
        id: 'orbitals',
        name: 'Orbitals',
        description: 'Orbs circle you, damaging enemies on contact.',
        icon: '🔵',
        pattern: 'auto_orbital',
        baseDamage: 8,
        baseCooldown: 0, // continuous
        orbitalCount: 2,
        orbitalRadius: 60,
        orbitalSpeed: 3, // radians per second
        hitRadius: 10,
        color: '#66AAFF',
        knockbackDist: 6,
        knockbackSpeed: 150,
        evolvesWithPassive: 'armor',
        evolutionId: 'guardian_ring',
    },
    poison: {
        id: 'poison',
        name: 'Poison Cloud',
        description: 'Drops toxic zone at your feet periodically.',
        icon: '☁️',
        pattern: 'auto_zone',
        baseDamage: 5,
        baseCooldown: 3.0,
        zoneRadius: 50,
        zoneDuration: 4.0,
        zoneTick: 0.5,
        color: '#66FF44',
        knockbackDist: 0,
        knockbackSpeed: 0,
        evolvesWithPassive: 'area',
        evolutionId: 'plague',
    },
    frostnova: {
        id: 'frostnova',
        name: 'Frost Nova',
        description: 'Periodic burst that freezes nearby enemies.',
        icon: '❄️',
        pattern: 'auto_burst',
        baseDamage: 8,
        baseCooldown: 4.0,
        burstRadius: 100,
        slowDuration: 2.0,
        slowFactor: 0.4,
        color: '#AADDFF',
        knockbackDist: 12,
        knockbackSpeed: 200,
        evolvesWithPassive: 'cooldown',
        evolutionId: 'absolute_zero',
    },
};

// Evolution definitions (replace weapon + consume passive)
export const EVOLUTIONS = {
    railgun: {
        id: 'railgun', name: 'Rail Gun', icon: '⚡🔫',
        description: 'Infinite pierce, extreme range.',
        pattern: 'aimed_single', baseDamage: 35, baseCooldown: 0.5,
        projectileSpeed: 1200, projectileRadius: 5, projectileLifetime: 2.0,
        projectileCount: 1, pierce: 999, spread: 0, color: '#88EEFF',
        knockbackDist: 8, knockbackSpeed: 300,
    },
    flak_cannon: {
        id: 'flak_cannon', name: 'Flak Cannon', icon: '💥💥',
        description: '9 exploding pellets.',
        pattern: 'aimed_spread', baseDamage: 8, baseCooldown: 0.9,
        projectileSpeed: 450, projectileRadius: 4, projectileLifetime: 0.6,
        projectileCount: 9, pierce: 0, spread: 0.5, aoeRadius: 30, color: '#FF6644',
        knockbackDist: 15, knockbackSpeed: 350,
    },
    minigun: {
        id: 'minigun', name: 'Minigun', icon: '🔥🔥',
        description: 'Extreme fire rate, no spread.',
        pattern: 'aimed_single', baseDamage: 5, baseCooldown: 0.04,
        projectileSpeed: 700, projectileRadius: 3, projectileLifetime: 0.7,
        projectileCount: 1, pierce: 0, spread: 0.02, color: '#FFCC00',
        knockbackDist: 4, knockbackSpeed: 200,
    },
    mirv: {
        id: 'mirv', name: 'MIRV', icon: '🚀💥',
        description: 'Splits into 6 mini-rockets on impact.',
        pattern: 'aimed_single', baseDamage: 40, baseCooldown: 2.5,
        projectileSpeed: 280, projectileRadius: 8, projectileLifetime: 2.0,
        projectileCount: 1, pierce: 0, aoeRadius: 120, mirvCount: 6, color: '#FF2200',
        knockbackDist: 50, knockbackSpeed: 500,
    },
    thunderstorm: {
        id: 'thunderstorm', name: 'Thunderstorm', icon: '⚡⚡',
        description: 'Chain to 5 enemies, auto-target, wider arc.',
        pattern: 'auto_chain', baseDamage: 20, baseCooldown: 0.7,
        chainRange: 200, chainCount: 4, chainArc: true, color: '#44EEFF',
        knockbackDist: 0, knockbackSpeed: 0,
    },
    inferno: {
        id: 'inferno', name: 'Inferno', icon: '🔥🌋',
        description: 'Wider cone, leaves lingering fire zones.',
        pattern: 'aimed_cone', baseDamage: 5, baseCooldown: 0.05,
        projectileSpeed: 350, projectileRadius: 5, projectileLifetime: 0.35,
        projectileCount: 2, spread: 0.6, color: '#FF4400',
        knockbackDist: 3, knockbackSpeed: 120,
        lingeringFire: true, lingerInterval: 3, lingerRadius: 30, lingerDuration: 3.0,
    },
    chakram: {
        id: 'chakram', name: 'Chakram', icon: '🪃💫',
        description: 'Faster spin, wider arc, multi-bounce.',
        pattern: 'auto_boomerang', baseDamage: 25, baseCooldown: 1.0,
        projectileSpeed: 500, projectileRadius: 10, projectileLifetime: 2.5,
        pierce: 99, color: '#22FFCC',
        knockbackDist: 20, knockbackSpeed: 280,
        isChakram: true,
    },
    guardian_ring: {
        id: 'guardian_ring', name: 'Guardian Ring', icon: '🔵🛡️',
        description: '8 orbs, larger radius, periodic damage pulse.',
        pattern: 'auto_orbital', baseDamage: 12, baseCooldown: 0,
        orbitalCount: 8, orbitalRadius: 90, orbitalSpeed: 4, hitRadius: 12,
        color: '#4488FF',
        knockbackDist: 10, knockbackSpeed: 200,
        pulseInterval: 2.0, pulseRadius: 120, pulseDamage: 20,
    },
    plague: {
        id: 'plague', name: 'Plague', icon: '☁️💀',
        description: 'Larger zone, spreads on kill, longer duration.',
        pattern: 'auto_zone', baseDamage: 8, baseCooldown: 2.5,
        zoneRadius: 80, zoneDuration: 6.0, zoneTick: 0.4,
        color: '#88FF22',
        knockbackDist: 0, knockbackSpeed: 0,
        isPlague: true,
    },
    absolute_zero: {
        id: 'absolute_zero', name: 'Absolute Zero', icon: '❄️💀',
        description: 'Larger radius, longer freeze, damage over time.',
        pattern: 'auto_burst', baseDamage: 15, baseCooldown: 3.5,
        burstRadius: 160, slowDuration: 4.0, slowFactor: 0.1,
        color: '#66CCFF',
        knockbackDist: 15, knockbackSpeed: 250,
        freezeDot: true, freezeDotDamage: 5, freezeDotTick: 0.5,
    },
};

// Level scaling: multipliers applied per weapon level
export function getWeaponStats(weaponId, level) {
    const base = WEAPONS[weaponId] || EVOLUTIONS[weaponId];
    if (!base) return null;

    const lvl = Math.max(1, Math.min(level, 8));
    const dmgMult = 1 + (lvl - 1) * 0.15;
    const cdMult = 1 - (lvl - 1) * 0.06;
    const countBonus = (lvl >= 3 ? 1 : 0) + (lvl >= 6 ? 1 : 0);
    const pierceBonus = lvl >= 5 ? 1 : 0;

    return {
        ...base,
        damage: base.baseDamage * dmgMult,
        cooldown: base.baseCooldown * Math.max(0.3, cdMult),
        projectileCount: (base.projectileCount || 0) + countBonus,
        pierce: (base.pierce || 0) + pierceBonus,
    };
}
